apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
spec:
  selector:
    matchLabels:
      app: nginx-demo
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
      - name: master
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /mnt # pod에서의 mount point
          name: pvc-volume
      volumes:
      - name: pvc-volume
        persistentVolumeClaim: #생성했던 pvc의 이름
          claimName: pvc
