kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: context-rolebinding
subjects:
- kind: ServiceAccount
  name: context-verfier
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin	
  apiGroup: rbac.authorization.k8s.io
